### ISSUE TITLE
if: Symbol's function definition is void: macrop

### ISSUE THREAD

**Issue by lecopivo** [rocher/ubuntu-theme#3]
I wanted to give your theme a try but when I execute `M-x load-theme RET ubuntu RET` I just receive message `if: Symbol's function definition is void: macrop`.

I commented out the whole `when` statement, I might have broken something but It works

```
(when (macrop 'fringe-helper-define)
   (fringe-helper-define 'git-gutter-fr+-added nil
   "......

   ...

)
```

**Comment by rocher** [comment]
These changes where integrated in the repository long time ago, but forgot to close this issue.
Thank you so much for your feedback, and sorry for the huge delay.
